/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gc171.hw2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        classUnderTest.getGreeting();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void boardDisplay() {
        Board tmp = new Board(20, 10);
        tmp.display();
    }


}
