/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece551.example;

import org.junit.Test;
import org.testng.annotations.AfterTest;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


}‹
